#!/usr/bin/env python3
"""
Firebase Firestore Seeding Script
Inject 50 dummy items into Firebase Firestore
"""

import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore
from datetime import datetime, timedelta
import random
import string

# Initialize Firebase Admin SDK
cred = credentials.Certificate('serviceAccountKey.json')
firebase_admin.initialize_app(cred)
db = firestore.client()

# Dropdown options from add_item.dart
CATEGORIES = ['Food', 'Fruit', 'Drink', 'Vegetable', 'Parcel']
MEASURES = ['PCS', 'KG', 'ML', 'LITER', 'BOX']

# Sample data lists
ITEM_NAMES = [
    'Apel Merah', 'Jeruk Manis', 'Pisang Cavendish', 'Mangga Harum Manis', 'Wortel Segar',
    'Brokoli Organik', 'Tomat Cherry', 'Bawang Merah', 'Telur Ayam Kampung', 'Susu UHT Putih',
    'Yogurt Strawberry', 'Keju Cheddar', 'Roti Gandum Utuh', 'Pasta Integral', 'Nasi Putih',
    'Teh Hitam Premium', 'Kopi Arabika Giling', 'Jus Apel Segar', 'Air Mineral Kemasan', 'Soda Lemon',
    'Mentega Tawar', 'Minyak Zaitun Extra Virgin', 'Gula Pasir Halus', 'Garam Laut', 'Merica Bubuk',
    'Tepung Terigu Protein Tinggi', 'Coklat Batang Hitam', 'Kacang Almond Panggang', 'Madu Asli', 'Selai Kacang Murni',
    'Ikan Salmon Atlantik', 'Daging Sapi Premium', 'Ayam Broiler Segar', 'Udang Vaname Beku', 'Cumi-cumi Segar',
    'Sayuran Organik Mix', 'Buah Naga Putih', 'Durian Montong Premium', 'Rambutan Manis', 'Nangka Muda',
    'Umbi-umbian Segar', 'Kembang Kol Organik', 'Bayam Hijau Segar', 'Kangkung Organik', 'Kemangi Segar',
    'Kemasan Parcel Premium', 'Hampers Lebaran Spesial', 'Box Makanan Ramah Lingkungan', 'Tas Belanja Kain', 'Kotak Makanan Bento'
]

SUPPLIERS = [
    'PT Segar Jaya', 'CV Petani Organik', 'Tani Sejahtera', 'Harum Manis Farm',
    'Agro Nusantara', 'Koperasi Tani Subur', 'Distributor Segar', 'Kebun Indah',
    'Petani Mitra', 'Suplai Segar Berkualitas'
]

def generate_item_code():
    """Generate random 6-character item code (lowercase + digits)"""
    chars = string.ascii_lowercase + string.digits
    return ''.join(random.choice(chars) for _ in range(6))

def generate_future_date():
    """Generate random expiry date between 30 and 365 days from now"""
    days = random.randint(30, 365)
    date = datetime.now() + timedelta(days=days)
    return date.strftime('%d/%m/%Y')

def create_dummy_item(index):
    """Create a single dummy item"""
    item_name = ITEM_NAMES[index % len(ITEM_NAMES)]
    
    # Determine category based on item type
    if index < 15:  # Fruits and vegetables
        category = random.choice(['Fruit', 'Vegetable'])
    elif index < 25:  # Dairy and baked goods
        category = 'Food'
    elif index < 35:  # Drinks
        category = 'Drink'
    elif index < 45:  # Proteins
        category = 'Food'
    else:  # Parcels
        category = 'Parcel'
    
    # Determine quantity and measure based on category
    if category == 'Drink':
        quantity = str(random.randint(10, 100))
        measure = random.choice(['ML', 'LITER'])
    elif category == 'Parcel':
        quantity = str(random.randint(1, 20))
        measure = 'BOX'
    elif category == 'Food':
        quantity = str(random.randint(5, 100))
        measure = random.choice(['PCS', 'KG'])
    else:  # Fruit, Vegetable
        quantity = str(random.randint(10, 500))
        measure = random.choice(['KG', 'PCS'])
    
    # Price calculation
    if category == 'Parcel':
        buy_rate = str(random.randint(100000, 500000))
        sell_rate = str(int(buy_rate) * random.uniform(1.15, 1.30))
    elif category == 'Drink':
        buy_rate = str(random.randint(3000, 15000))
        sell_rate = str(int(buy_rate) * random.uniform(1.20, 1.40))
    else:
        buy_rate = str(random.randint(5000, 50000))
        sell_rate = str(int(buy_rate) * random.uniform(1.20, 1.50))
    
    sell_rate = str(int(float(sell_rate)))
    
    now = datetime.now()
    
    item = {
        'uid': '',  # Will be generated by Firestore
        'item_name': f"{item_name} #{index + 1}",
        'item_code': generate_item_code(),
        'category': category,
        'quantity': quantity,
        'previous_quantity': quantity,
        'buy_rate': buy_rate,
        'sell_rate': sell_rate,
        'expired_date': generate_future_date(),
        'measure': measure,
        'supplier': random.choice(SUPPLIERS),
        'description': f"Dummy data for testing - {item_name} batch #{index + 1}",
        'image_url': '',
        'status': random.choice(['active', 'inactive']),
        'created_by': 'seed@vreetory.com',
        'updated_by': 'seed@vreetory.com',
        'created_at': now,
        'updated_at': now,
    }
    
    return item

def seed_firebase(num_items=50):
    """Seed Firebase with dummy items"""
    print(f"Starting to seed {num_items} dummy items to Firebase...")
    
    items_collection = db.collection('items')
    batch = db.batch()
    batch_count = 0
    batch_size = 10  # Firestore batch write limit
    
    for i in range(num_items):
        item = create_dummy_item(i)
        
        # Add new document, let Firestore generate ID
        doc_ref = items_collection.document()
        item['uid'] = doc_ref.id
        
        batch.set(doc_ref, item)
        batch_count += 1
        
        # Commit batch every batch_size items
        if batch_count >= batch_size:
            batch.commit()
            print(f"✓ Committed {batch_count} items (total: {i + 1}/{num_items})")
            batch = db.batch()
            batch_count = 0
    
    # Commit remaining items
    if batch_count > 0:
        batch.commit()
        print(f"✓ Committed {batch_count} items (total: {num_items}/{num_items})")
    
    print(f"\n✅ Successfully seeded {num_items} dummy items to Firebase Firestore!")
    print("Items are now available in the 'items' collection.")

if __name__ == '__main__':
    try:
        seed_firebase(50)
    except FileNotFoundError:
        print("❌ Error: serviceAccountKey.json not found!")
        print("Please download your Firebase service account key and place it in the project root directory.")
        print("\nSteps to get serviceAccountKey.json:")
        print("1. Go to Firebase Console: https://console.firebase.google.com/")
        print("2. Select your project: vreetory-app")
        print("3. Go to Project Settings > Service Accounts")
        print("4. Click 'Generate New Private Key'")
        print("5. Save as 'serviceAccountKey.json' in the project root")
    except Exception as e:
        print(f"❌ Error: {e}")
