// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq0b1PvKQHCMhkwSGi1JBpje5v9kUTHZg',
    appId: '1:124419940113:web:eea3fdda53b12bd1af36b0',
    messagingSenderId: '124419940113',
    projectId: 'vreetory-app',
    authDomain: 'vreetory-app.firebaseapp.com',
    storageBucket: 'vreetory-app.firebasestorage.app',
    measurementId: 'G-LWN3YJ3KBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVtlqEXZVhu2sNG5mxaD9T_YdJUpOaRCo',
    appId: '1:124419940113:android:f1ed412ed777145eaf36b0',
    messagingSenderId: '124419940113',
    projectId: 'vreetory-app',
    storageBucket: 'vreetory-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA85Km_dzm8AhtQMxg0S44MDAAWHSKKkmY',
    appId: '1:124419940113:ios:2cb2c8d5b1bb062faf36b0',
    messagingSenderId: '124419940113',
    projectId: 'vreetory-app',
    storageBucket: 'vreetory-app.firebasestorage.app',
    iosBundleId: 'com.example.vreetoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA85Km_dzm8AhtQMxg0S44MDAAWHSKKkmY',
    appId: '1:124419940113:ios:2cb2c8d5b1bb062faf36b0',
    messagingSenderId: '124419940113',
    projectId: 'vreetory-app',
    storageBucket: 'vreetory-app.firebasestorage.app',
    iosBundleId: 'com.example.vreetoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq0b1PvKQHCMhkwSGi1JBpje5v9kUTHZg',
    appId: '1:124419940113:web:44538c819cb3d191af36b0',
    messagingSenderId: '124419940113',
    projectId: 'vreetory-app',
    authDomain: 'vreetory-app.firebaseapp.com',
    storageBucket: 'vreetory-app.firebasestorage.app',
    measurementId: 'G-B84SGJ5XCF',
  );
}